# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Tiny Blackjack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tiny Blackjack
  pod 'SwiftState', :git => 'https://github.com/ReactKit/SwiftState', :submodules => true
  pod 'SwiftySound'
  pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner'
  
  target 'Tiny BlackjackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
