# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane(nightly: true)

default_platform(:ios)

desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    ensure_git_status_clean

    increment_build_number(
      build_number: Time.now.to_i
    )
   
    increment_version_number
    build_number = get_build_number
    version_number = get_version_number
    changelog = read_changelog

    sync_code_signing(type: "appstore",
      app_identifier: "nl.simpletechture.Tiny-Converter",
      git_url: "https://github.com/PatrickKalkman/certificates",
      username: "patrick@simpletechture.nl", 
      team_name: "Patrick Kalkman")

    build_app(scheme: "Tiny Converter",
      clean: true,
      export_method: "app-store",)

    upload_to_testflight(wait_for_uploaded_build: true,
                         changelog: changelog,
                         distribute_external: true,
                         username: "patrick@simpletechture.nl",
                         team_name: "Patrick Kalkman",
                         skip_waiting_for_build_processing: true)

    stamp_changelog(section_identifier: "Version #{version_number}, Build #{build_number}") # Stamp Unreleased section with newly released build number

    clean_build_artifacts

    # commit to git the changes from bumping version number
    commit_version_bump(message: "Committed version bump",
                        include: "CHANGELOG.md")
  end