# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Tiny Timer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tiny Timer
  pod 'Firebase/Core'
  pod 'SCLAlertView'
  pod 'SPStorkController'
  pod 'SparrowKit'
  pod 'SPFakeBarView'

end
